package com.xtremand.common.bom;
/**
 * FindLevel decides how many associations of an Object should be loaded
 * @author Ramesh
 * @since 8/16/2016
 * @version 1.0
 *
 */
public enum FindLevel {
	SHALLOW,
	VIDEO_FILES,
	USERS,
	CAMPAIGNS,
	FOLLOWCUSTOMERS, 
	CAMPAIGNPROGRAMS, 
	SUB_CATEGORIES, 
	CUSTOMERS, 
	SUB_SCRIPTIONS, 
	USER_LISTS, 
	VIDEO_TAGS, 
	VIDEO_PATH,
	INCREMENT_VIEW,
	FAVORITE,
	ROLES,
	CAMPAIGN_EMAIL_TEMPLATE,
	VIDEO_IMAGE,
	VIDEO_CONTROL,
	CAMPAIGN_REPLIES,
	CAMPAIGN_URLS,
	COMPANY_PROFILE,
	PARTNER_COMPANY, 
	USER_USER_LIST, 
	CAMPAIGN_EVENT_TIMES,
	CAMPAIGN_EVENT_MEDIA,
	CAMPAIGN_FORM,
	CAMPAIGN_FORM_SUBMIT,
	CALL_ACTION,
	SPAM_SCORE
}
