package com.xtremand.form.bom;

public enum FormDefaultFieldTypeEnum {
	AMOUNT("AMOUNT"), CLOSE_DATE("CLOSE_DATE"), DEAL_NAME("DEAL_NAME"), DEAL_ID("DEAL_ID"), LEAD_ID("LEAD_ID"), CREATED_BY_NAME("CREATED_BY_NAME"), XAMPLIFY_LEAD_CREATED_DATE("XAMPLIFY_LEAD_CREATED_DATE"), XAMPLIFY_DEAL_REGISTERED_DATE("XAMPLIFY_DEAL_REGISTERED_DATE"),
	CONTACT_FIRST_NAME("CONTACT_FIRST_NAME"), CONTACT_LAST_NAME("CONTACT_LAST_NAME"), CONTACT_EMAIL("CONTACT_EMAIL"), CONTACT_PHONE_NUMBER("CONTACT_PHONE_NUMBER"), CONTACT_STREET("CONTACT_STREET"), CONTACT_ZIP_CODE("CONTACT_ZIP_CODE"), CONTACT_STATE("CONTACT_STATE"),
	CONTACT_CITY("CONTACT_CITY"), CONTACT_COUNTRY("CONTACT_COUNTRY"), CONTACT_COMPANY_NAME("CONTACT_COMPANY_NAME"), CONTACT_TITLE("CONTACT_TITLE"), XAMPLIFY_LEAD_REGISTERED_DATE("XAMPLIFY_LEAD_REGISTERED_DATE"), PIPELINE_STAGE("PIPELINE_STAGE");

	protected String type;

	private FormDefaultFieldTypeEnum(String type) {
		this.type = type;
	}

	public String getType() {
		return type;
	}
}
