package com.xtremand.vanity.email.templates.bom;

public enum DefaultEmailTemplateType {
	JOIN_MY_TEAM("JOIN_MY_TEAM"), ACCOUNT_ACTIVATION("ACCOUNT_ACTIVATION"), FORGOT_PASSWORD("FORGOT_PASSWORD"),
	JOIN_VENDOR_COMPANY("JOIN_VENDOR_COMPANY"), TRACK_PUBLISH("TRACK_PUBLISH"), PLAYBOOK_PUBLISH("PLAYBOOK_PUBLISH"),
	ASSET_PUBLISH("ASSET_PUBLISH"), SHARE_LEAD("SHARE_LEAD"), ONE_CLICK_LAUNCH("ONE_CLICK_LAUNCH"),
	PAGE_CAMPAIGN_PARTNER("PAGE_CAMPAIGN_PARTNER"), PAGE_CAMPAIGN_CONTACT("PAGE_CAMPAIGN_CONTACT"),
	SOCIAL_CAMPAIGN("SOCIAL_CAMPAIGN"), TO_SOCIAL_CAMPAIGN("TO_SOCIAL_CAMPAIGN"), JOIN_PRM_COMPANY("JOIN_PRM_COMPANY"),
	ADD_LEAD("ADD_LEAD"), ADD_DEAL("ADD_DEAL"), LEAD_UPDATE("LEAD_UPDATE"), DEAL_UPDATE("DEAL_UPDATE"),
	ADD_SELF_LEAD("ADD_SELF_LEAD"), ADD_SELF_DEAL("ADD_SELF_DEAL"), UPDATE_SELF_LEAD("UPDATE_SELF_LEAD"),
	UPDATE_SELF_DEAL("UPDATE_SELF_DEAL"), PRM_ADD_LEAD("PRM_ADD_LEAD"), PRM_UPDATED("PRM_UPDATED"),
	PARTNER_REMAINDER("PARTNER_REMAINDER"), COMPANY_PROFILE_INCOMPLETE("COMPANY_PROFILE_INCOMPLETE"),
	FORM_COMPLETED("FORM_COMPLETED"), JOIN_VERSA_TEAM("JOIN_VERSA_TEAM"), UNLOCK_MDF_FUNDING("UNLOCK_MDF_FUNDING"),
	LEAD_APPROVE("LEAD_APPROVE"),LEAD_REJECT("LEAD_REJECT"),PRM_LEAD_APPROVE("PRM_LEAD_APPROVE"),
	PRM_LEAD_REJECT("PRM_LEAD_REJECT"),TEAM_MEMBER_PORTAL("TEAM_MEMBER_PORTAL"),PARTNER_ADD_LEAD("PARTNER_ADD_LEAD"),
	PRM_PARTNER_ADD_LEAD("PRM_PARTNER_ADD_LEAD"),PARTNER_UPDATE_LEAD("PARTNER_UPDATE_LEAD"),
	PRM_PARTNER_UPDATE_LEAD("PRM_PARTNER_UPDATE_LEAD"),PARTNER_ADD_DEAL("PARTNER_ADD_DEAL"),PARTNER_UPDATE_DEAL("PARTNER_UPDATE_DEAL"),
	PARTNER_SIGNATURE_PENDING("PARTNER_SIGNATURE_PENDING"),LEAD_DETAILS_UPDATE("LEAD_DETAILS_UPDATE"),
	PARTNER_SIGNATURE_ENABLED("PARTNER_SIGNATURE_ENABLED"),PARTNER_PDF_SIGNATURE_COMPLETED("PARTNER_PDF_SIGNATURE_COMPLETED"),
	LEAD_STATUS_REMINDER_NOTIFICATION("LEAD_STATUS_REMINDER_NOTIFICATION"),WELCOME_EMAIL_REMAINDER("WELCOME_EMAIL_REMAINDER"),
	PRM_LEAD_STATUS_REMINDER_NOTIFICATION("PRM_LEAD_STATUS_REMINDER_NOTIFICATION");


	protected String type;

	private DefaultEmailTemplateType(String type) {
		this.type = type;
	}

	public String getType() {
		return type;
	}
}
